### PR TITLE
Expose the Yaml definition to consumers

### PR DESCRIPTION
**Pull request by alexandcote**
I don't think it's currently possible to use the default list of regex and add some custom regex. Right now, we need to copy the regex list in our project and add our custom regex to this copied list. I propose to expose the list so we can merge our custom regex with the default list.

Note: I'm really new to go. In fact, it's the first time I'm working on a go project. Suggestions are welcome 😃

cc @elsigh

### CODE REVIEW

**Comment by elsigh** [comment]
Why would you want to "add custom regex" without just adding them to the uap-core repo?

**Comment by alexandcote** [comment]
Those UAs are only for internal purposes and the community will not benefit from those additions.

**Comment by elsigh** [comment]
Can you describe how this change enables what you want to do? I don't see why you couldn't append to the yaml file before loading/compiling the parser.

**Comment by alexandcote** [comment]
@elsigh again, I'm really new to Go but here is my pseudo code.

```go
import "github.com/ua-parser/uap-go/uaparser"

var customDefinition = []byte(`user_agent_parsers
  - regex: 'My Custom UA/(\d+).'
     family_replacement: 'My Custom UA'
     v1_replacement: '$1'
...
`)

var uaRegexes = mergeRegex(customDefinition, uaparser.DefinitionYaml)
var uaParser, _ = uaparser.NewFromBytes(uaRegexes)
```

The issue is `uaparser.DefinitionYaml` is not accessible.

**Comment by elsigh** [comment]
Could you not just use a script to append to the yaml.go text file itself without doing this at runtime?

**Comment by alexandcote** [comment]
I could, but it's not just appending. We need to deeply merge the YAML file and order matters. But yes I could use this strategy. One thing to keep in mind is if someone wants to conditionally add regex this strategy will not work.

**Comment by elsigh** [comment]
What do you mean that it's not appending? You cannot write to the yaml file on disk?

**Comment by alexandcote** [comment]
It's not a YAML file, it's the `yaml.go`. If the regex was exposed from a YAML file I could easily merge it with my custom one. But here I have to parse the code and inject my custom regex. It's a bit harder than doing it on the run time.

Maybe we can expose the YAML file and the`yaml.go` file. So I can run a script similar to what we have in this library?

Any thought?

**Comment by elsigh** [comment]
I'm not an active user of this project at the moment so I wonder if anyone else has an opinion.. All in all I'm reluctant about the idea that the list of UAs be modifiable at run time but I'm happy to merge this as is and then we can revert if someone objects.

**Pull request merged**
