### PR TITLE
performance improvements

### PR DESCRIPTION
**Pull request by evgenigourvitch**
Hello guys,

We are using this kindly shared package and since we are using it in heavy loaded server environment (~400K requests/sec) each millisecond counts, so I added some flexibility to
 the current implementation without affecting the base capabilities.
It allows to detect only selected parts (for example not to parse Device if not needed, like in our use-case).
I've also added some sorting capability of the regexp arrays to allow to reshuffle them into descending order by the most successful matches.

May be you will find it usable.
Best regards and thank you for the incredible package!

### CODE REVIEW

**Comment by elsigh** [comment]
Can you try the perf benchmarks with this change? See https://github.com/ua-parser/uap-go/pull/26

**Comment by evgenigourvitch** [comment]
=== RUN   TestOSParsing
--- PASS: TestOSParsing (0.04s)
=== RUN   TestUAParsing
=== RUN   TestDeviceParsing
=== RUN   TestGenericParseMethodConcurrency
--- PASS: TestGenericParseMethodConcurrency (0.51s)
--- PASS: TestDeviceParsing (9.01s)
--- PASS: TestUAParsing (14.64s)
PASS
**

> BenchmarkParser-4           	      50	  22327841 ns/op
> BenchmarkParserWithOptions-4	     100	  12900935 ns/op

**
ok  	github.com/streamrail/uap-go.evg/uaparser	17.813s

**Comment by elsigh** [comment]
Is this PR the source of Issue #33?

**Comment by evgenigourvitch** [comment]
Actually, I can see no issue, but as designed behaviour, like I discribed
in the issue's comment.
Thanks.

**Pull request merged**
