### PR TITLE
Updated submodule uap-core to 0.9.0

### PR DESCRIPTION
**Pull request by Tigraine**
Updates to latest release of uap-core 0.9.0 that also includes Chromium Edge

### CODE REVIEW

**Comment by Tigraine** [comment]
Noticed (after trying for a long time) that I had to re-generate `yaml.go` - now the PR should be good to go

**Comment by Tigraine** [comment]
@elsigh Is there anything I can do to help get this merged? Anything missing from the PR?

**Comment by elsigh** [comment]
and now we really oughta update to 0.10.0 as well. Sorry for the delay here, it's not because I had any objections it just feel through my notification cracks.

**Comment by Tigraine** [comment]
> and now we really oughta update to 0.10.0 as well. Sorry for the delay here, it's not because I had any objections it just feel through my notification cracks.

no problem -> https://github.com/ua-parser/uap-go/pull/72 ;)

**Pull request merged**
