### PR TITLE
Optimize for top-user-agents

### PR DESCRIPTION
**Pull request by dzbarsky**
Teaches the build script to clone top UAs and optimize the matching order accordingly. This leads to huge speedups in real-world (browser) usage.

### CODE REVIEW

**Comment by elsigh** [comment]
I'm not against optimization, but this makes the implementation more complicated - do you have any numbers to justify this change? I'd really love a current team/person depending on this library to weigh in..

**Comment by dzbarsky** [comment]
I don't think it makes the implementation more complicated - all it does is reorder the list of regexes we test against. In fact, the library implementation is exactly the same. The diff looks big because my editor ran `gofmt` and removed oddities like trailing semicolons, etc.

As for numbers, I believe I saw around 100x+ speedup on UA parsing, with this change UA parsing disappears from profiles. Intuitively, it makes sense that testing the conditions that are likeliest to match upfront will result in better performance.

**Comment by dgoldstein0** [comment]
hm, if yaml.go file is just a golang translation of the data in https://github.com/ua-parser/uap-core/blob/master/regexes.yaml then sorting it likely has implications for correctness: the list of regexes is expected to be applied //in order//, and it's not guaranteed that matches will be mutually exclusive - user agents are strange, terrible strings where some browsers try to look like other browsers, and so matching the unusual special cases first, which the regexes.yaml explicitly intends, does make some sense.  That said... the test yaml included with uap-core is pretty extensive and if you don't fail any of those tests that's a good sign this could work.

That said the main perf optimization I've seen in uap-python, which afaict is missing in this golang version, is caching the results; since probably 98%+ of traffic to a typical web service is just various versions of Chrome, Safari, Firefox, Edge, it's easy to get a lot of mileage out of a cache of around a 1000 entries, give or take a bit.

I also wonder if such reordering would be better contributed to uap-core - there, it'd help all the user agent parser libraries, and not just one.

**Comment by dgoldstein0** [comment]
... and speaking of which, PR #75 had the same caching idea.

**Comment by elsigh** [comment]
I think you can memoize and implement caching easily in userland code.

**Comment by dgoldstein0** [comment]
true, BUT why should we have to implement this at each caller, rather than have it in the library?  One of the things that makes this worse is that other uap libraries already do it - our main usage of user agent parser where I work is uap-go and uap-python - and uap-python already has this behavior https://github.com/ua-parser/uap-python/blob/0.x/ua_parser/user_agent_parser.py#L219-L249.  So it's not unreasonable that we assume uap-go does as well.

**Comment by elsigh** [comment]
Are you interested in maintaining the lib / go implementation? If so, I'm
game

**Comment by dgoldstein0** [comment]
sure.

**Comment by elsigh** [comment]
invite sent. Bottom line is that I'm not using anything that depends on this lib today in production and won't be able to follow up with fixes/bug reports from a change like this, but I get it and I'm totally supportive of making the lib better.

**Comment by dgoldstein0** [comment]
well now that I have maintainer power I guess I'll make that official - caching is the lower risk approach so I'd rather pursue that.  if you want to optimize the regex order, I think that should be a PR to uap-core instead.

**Pull request closed without merging**
