### PR TITLE
Update uap-core to f249dd

### PR DESCRIPTION
**Pull request by F21**

### CODE REVIEW

**Comment by F21** [comment]
The build fails because the repo is missing a .travis.yaml, so it uses default configs which runs `rake`, but there is no `rakefile` in the repo.

**Comment by F21** [comment]
Will need to rebase against #42 for the tests to work.

**Comment by F21** [comment]
It seems a test case is failing. The problem is probably in uap-core.

**Comment by elsigh** [comment]
I am on vacation and can't really investigate but if you figure it out I can merge pretty easily.

**Comment by F21** [comment]
ping @elsigh This seems to be fixed after updating `uap-core` to the latest commit.

**Pull request merged**
